[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = [
  "bun install --frozen-lockfile"
]

[phases.build]
cmds = [
  "bun run db:generate",
  "bun run db:deploy",
  "cd apps/server && bun run compile",
  "find . -name node_modules -type d -prune -exec rm -rf '{}' +"
]

[start]
cmd="/app/apps/server/server"